#!/usr/bin/env python3
"""Generate Rust flag metadata from the existing Orion C++ asset table.

This keeps the Rust port aligned with the already-generated `flags.bin` payload
until the downloader/resizer pipeline is moved over fully.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROW_RE = re.compile(
    r'\{"(?P<code>[^"]+)",\s*"(?P<name>[^"]+)",\s*'
    r'(?P<width>\d+),\s*(?P<height>\d+),\s*(?P<offset>\d+)\}'
)


def parse_rows(source: Path) -> list[tuple[str, str, int, int, int]]:
    rows: list[tuple[str, str, int, int, int]] = []
    for match in ROW_RE.finditer(source.read_text()):
        rows.append(
            (
                match.group("code"),
                match.group("name"),
                int(match.group("width")),
                int(match.group("height")),
                int(match.group("offset")),
            )
        )
    if not rows:
        raise SystemExit(f"no flag rows found in {source}")
    return rows


def write_rust(rows: list[tuple[str, str, int, int, int]], output: Path) -> None:
    lines = [
        "// Generated by tools/generate_flags_assets.py; do not edit by hand.",
        "use crate::flags::FlagAsset;",
        "",
        f"pub const FLAG_ASSET_COUNT: usize = {len(rows)};",
        "pub const FLAG_ASSETS: [FlagAsset; FLAG_ASSET_COUNT] = [",
    ]
    for code, name, width, height, offset in rows:
        lines.append(
            f'    FlagAsset {{ code: "{code}", name: "{name}", '
            f"width: {width}, height: {height}, offset: {offset} }},"
        )
    lines.extend(["];", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("../orion/main/flags_assets.cpp"),
        help="existing C++ flags_assets.cpp path",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("crates/orion-core/src/generated/flags_assets.rs"),
        help="Rust metadata output path",
    )
    args = parser.parse_args()
    write_rust(parse_rows(args.source), args.output)


if __name__ == "__main__":
    main()

