#!/usr/bin/env python3
"""Generate Rust flag metadata from the existing Orion flag asset table.

This keeps the Rust port aligned with the already-generated `flags.bin` payload
until the downloader/resizer pipeline is moved over fully.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROW_RE = re.compile(
    r'\{"(?P<code>[^"]+)",\s*"(?P<name>[^"]+)",\s*'
    r'(?P<width>\d+),\s*(?P<height>\d+),\s*(?P<offset>\d+)\}'
)
RUST_ROW_RE = re.compile(
    r'FlagAsset\s*\{\s*code:\s*"(?P<code>[^"]+)",\s*'
    r'name:\s*"(?P<name>[^"]+)",\s*'
    r'width:\s*(?P<width>\d+),\s*height:\s*(?P<height>\d+),\s*'
    r'offset:\s*(?P<offset>[\d_]+)'
)


Row = tuple[str, str, int, int, int]
CompressedRow = tuple[str, str, int, int, int, int]


def parse_rows(source: Path) -> list[Row]:
    rows: list[Row] = []
    for match in ROW_RE.finditer(source.read_text()):
        rows.append(
            (
                match.group("code"),
                match.group("name"),
                int(match.group("width")),
                int(match.group("height")),
                int(match.group("offset")),
            )
        )
    if not rows:
        raise SystemExit(f"no flag rows found in {source}")
    return rows


def parse_rust_rows(source: Path) -> list[Row]:
    rows: list[Row] = []
    for match in RUST_ROW_RE.finditer(source.read_text()):
        rows.append(
            (
                match.group("code"),
                match.group("name"),
                int(match.group("width")),
                int(match.group("height")),
                int(match.group("offset").replace("_", "")),
            )
        )
    if not rows:
        raise SystemExit(f"no flag rows found in {source}")
    return rows


def compress_flags(rows: list[Row], raw_input: Path, compressed_output: Path) -> list[CompressedRow]:
    raw = raw_input.read_bytes()
    compressed = bytearray()
    compressed_rows: list[CompressedRow] = []
    for code, name, width, height, raw_offset in rows:
        raw_len = width * height * 2
        end = raw_offset + raw_len
        if end > len(raw):
            raise SystemExit(f"{code} extends past {raw_input}")
        image = raw[raw_offset:end]
        compressed_offset = len(compressed)
        pos = 0
        while pos < len(image):
            pixel = image[pos : pos + 2]
            count = 1
            pos += 2
            while pos < len(image) and count < 0xFFFF and image[pos : pos + 2] == pixel:
                count += 1
                pos += 2
            compressed.extend(count.to_bytes(2, "little"))
            compressed.extend(pixel)
        compressed_rows.append(
            (code, name, width, height, compressed_offset, len(compressed) - compressed_offset)
        )
    compressed_output.parent.mkdir(parents=True, exist_ok=True)
    compressed_output.write_bytes(compressed)
    return compressed_rows


def write_rust(rows: list[CompressedRow], output: Path) -> None:
    lines = [
        "// Generated by tools/generate_flags_assets.py; do not edit by hand.",
        "use crate::flags::FlagAsset;",
        "",
        f"pub const FLAG_ASSET_COUNT: usize = {len(rows)};",
        "pub const FLAG_ASSETS: [FlagAsset; FLAG_ASSET_COUNT] = [",
    ]
    for code, name, width, height, offset, data_len in rows:
        lines.append(
            f'    FlagAsset {{ code: "{code}", name: "{name}", '
            f"width: {width}, height: {height}, offset: {offset}, data_len: {data_len} }},"
        )
    lines.extend(["];", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("../orion/main/flags_assets.cpp"),
        help="existing C++ flags_assets.cpp path",
    )
    parser.add_argument(
        "--source-format",
        choices=("cpp", "rust"),
        default="cpp",
        help="asset metadata source format",
    )
    parser.add_argument(
        "--raw-bin",
        type=Path,
        default=Path("main/flags.bin"),
        help="raw RGB565 flag payload",
    )
    parser.add_argument(
        "--compressed-output",
        type=Path,
        default=Path("main/flags.rle"),
        help="compressed RLE RGB565 flag payload",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("crates/orion-core/src/generated/flags_assets.rs"),
        help="Rust metadata output path",
    )
    args = parser.parse_args()
    rows = parse_rows(args.source) if args.source_format == "cpp" else parse_rust_rows(args.source)
    write_rust(compress_flags(rows, args.raw_bin, args.compressed_output), args.output)


if __name__ == "__main__":
    main()
